### ISSUE TITLE
finish_loading() hook dead/not working

### ISSUE THREAD

**Issue by MajorPain1** [StarrFox/wizwalker#17]
Traceback (most recent call last):
  File "C:\Users\user\Documents\WizSDKScripts\DoomsdayKrok\DoomsdayKrok.py", line 232, in run
    await main()
  File "C:\Users\user\Documents\WizSDKScripts\DoomsdayKrok\DoomsdayKrok.py", line 83, in main
    await p2.finish_loading()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\wizsdk\client.py", line 405, in finish_loading
    await asyncio.wait_for(_loading_coro(), timeout=timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\wizsdk\client.py", line 395, in _loading_coro
    player_struct = base_addr()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\wizsdk\client.py", line 392, in <lambda>
    base_addr = lambda: self.walker._memory.process.read_int(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pymem__init__.py", line 476, in read_int
    value = pymem.memory.read_int(self.process_handle, address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pymem\memory.py", line 271, in read_int
    bytes = read_bytes(handle, address, struct.calcsize('i'))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pymem\memory.py", line 97, in read_bytes
    raise TypeError('Address must be int: {}'.format(address))
TypeError: Address must be int: None
Un-hooking all registered clients

Example of finish_loading not working

**Comment by StarrFox** [comment]
I don't have any functions called finish_loading; can you make an example of this issue using just wizwalker
