### ISSUE TITLE
Memory scanning issue with hooks

### ISSUE THREAD

**Issue by StarrFox** [StarrFox/wizwalker#5]
Some users are experiencing an error while hooking

```
Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\cli\console.py", line 137, in hook_command
    await client.activate_hooks(target_hook.replace(" ", "_"))
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\client.py", line 70, in activate_hooks
    await hook()
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\windows\memory\handler.py", line 36, in wrapped
    return await function(*args, **kwargs)
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\utils.py", line 61, in sync_wrapper
    return await loop.run_in_executor(pool, internal_function)
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\windows\memory\handler.py", line 283, in hook_player_struct
    player_hook.hook()
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\windows\memory\hooks.py", line 67, in hook
    self.jump_bytecode = self.get_jump_bytecode()
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\wizwalker\windows\memory\hooks.py", line 118, in get_jump_bytecode
    distance = self.hook_address - self.jump_address
TypeError: unsupported operand type(s) for -: 'int' and 'list'
```

this is caused by [this line](https://github.com/srounet/Pymem/blob/master/pymem/pattern.py#L41) in pymem

This seems to be a memory protection issue which is strange because it doesn't affect everyone

**Comment by StarrFox** [comment]
fixed in fa0232c690bebe7d6c718354cbd4fd9c9ed27dc7
